# CMake generated Testfile for 
# Source directory: E:/LinearProgramingSolver
# Build directory: E:/LinearProgramingSolver/build-umfpack
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[smoke_test]=] "E:/LinearProgramingSolver/build-umfpack/Debug/lp_solver_smoke_tests.exe")
  set_tests_properties([=[smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;92;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[smoke_test]=] "E:/LinearProgramingSolver/build-umfpack/Release/lp_solver_smoke_tests.exe")
  set_tests_properties([=[smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;92;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[smoke_test]=] "E:/LinearProgramingSolver/build-umfpack/MinSizeRel/lp_solver_smoke_tests.exe")
  set_tests_properties([=[smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;92;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[smoke_test]=] "E:/LinearProgramingSolver/build-umfpack/RelWithDebInfo/lp_solver_smoke_tests.exe")
  set_tests_properties([=[smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;92;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
else()
  add_test([=[smoke_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[stress_test]=] "E:/LinearProgramingSolver/build-umfpack/Debug/lp_solver_stress_tests.exe")
  set_tests_properties([=[stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;100;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[stress_test]=] "E:/LinearProgramingSolver/build-umfpack/Release/lp_solver_stress_tests.exe")
  set_tests_properties([=[stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;100;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[stress_test]=] "E:/LinearProgramingSolver/build-umfpack/MinSizeRel/lp_solver_stress_tests.exe")
  set_tests_properties([=[stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;100;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[stress_test]=] "E:/LinearProgramingSolver/build-umfpack/RelWithDebInfo/lp_solver_stress_tests.exe")
  set_tests_properties([=[stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;100;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
else()
  add_test([=[stress_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[advanced_features_test]=] "E:/LinearProgramingSolver/build-umfpack/Debug/lp_solver_advanced_features_tests.exe")
  set_tests_properties([=[advanced_features_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;108;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[advanced_features_test]=] "E:/LinearProgramingSolver/build-umfpack/Release/lp_solver_advanced_features_tests.exe")
  set_tests_properties([=[advanced_features_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;108;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[advanced_features_test]=] "E:/LinearProgramingSolver/build-umfpack/MinSizeRel/lp_solver_advanced_features_tests.exe")
  set_tests_properties([=[advanced_features_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;108;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[advanced_features_test]=] "E:/LinearProgramingSolver/build-umfpack/RelWithDebInfo/lp_solver_advanced_features_tests.exe")
  set_tests_properties([=[advanced_features_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/LinearProgramingSolver/CMakeLists.txt;108;add_test;E:/LinearProgramingSolver/CMakeLists.txt;0;")
else()
  add_test([=[advanced_features_test]=] NOT_AVAILABLE)
endif()
